---
- hosts: all

  vars:
    email: test@example.com
    domain: example.com
    collector_name: user

  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install apache and php.
    become: yes
    apt: 
      name: 
        - apache2
        - php 
        - libapache2-mod-php
        - php-mysql
        - snapd
      state: latest

  - name: Allow apache in ufw.
    become: yes
    community.general.ufw: 
      rule: allow
      name: Apache

  - name: install certbot
    become: yes
    community.general.snap: 
      name: certbot
      classic: true



  - name: Get certificate
    command: sudo certbot certonly --standalone --email {{email}} --domain {{ domain }} --agree-tos --non-interactive
    args:
      creates: /etc/letsencrypt/live/{{ domain }}
    ignore_errors: true # for testing on vm without public ip

    
  - name: Setup cronjob for renewal
    cron:
      name: certbot-renewal
      job: "/bin/bash -lc 'certbot -q renew'"
      minute: "0"
      hour: "14"

  - name: Install postfix, dovecot, roundcube
    become: yes
    apt: 
      name: 
        - postfix
        - dovecot-core
        - dovecot-imapd
        - dovecot-pop3d
        - dovecot-lmtpd
        - roundcube-sqlite3
      state: latest


  - name: Add collector to postfix
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/postfix/virtual_aliases
      state: present
      create: true
      line: '@{{domain}}       {{collector_name}}@{{domain}}'

  - name: Configure postfix
    become: yes
    ansible.builtin.template: 
      src: ./templates/main.cf.j2
      dest: /etc/postfix/main.cf

 


# TODOs
# add virtual mailboxes
# copy template
# configure dovecot
# configure roundcube

